config/routes.rb
Rails.application.routes.draw do
    resources :tweets
    root 'tweets#index'
    get 'tweets/index'
    get 'tweets/new',to: 'tweets#new'
    post 'tweets', to: 'tweets#create'
    delete 'tweets/:id', to: 'tweets#destroy'
    get 'tweets/:id' , to: 'tweets#show'
    get 'tweets/:id/edit', to: 'tweets#edit'
    patch 'tweets/:id', to: 'tweets#update'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message, presence: true
    validates :message, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    def new
        @tweet = Tweet.new
    end
    def create
        @tweet = Tweet.new(message: params[:tweet][:message], tdate: Time.current)
        if @tweet.save
            flash[:notice] = '1レコード追加しました。'
            redirect_to '/' 
        else
            render 'new'
        end
    end
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        flash[:notice] = '1レコード削除しました。'
        redirect_to '/'
    end
    def show
        @tweet = Tweet.find(params[:id])
    end
    def edit
        @tweet = Tweet.find(params[:id])
    end
    def update
        @tweet = Tweet.find(params[:id])
        @tweet.update(message: params[:tweet][:message], tdate: Time.current)
        if @tweet.save
            flash[:notice] = '1レコード変更しました。'
            redirect_to '/' 
        else
            render 'new'
        end 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta charset="UTF-8">
    <link href="tweets/style.css" rel="stylesheet">
  </head>

  <body>
    <div id="container">
      
      <div id="header">
        <%= render "header" %>
      </div>
      
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      
      <div id="content">
        <%= yield %>
      </div>
      
      <div id="footer">
      <%= render "footer" %>
      </div>
      
    </div>
  </body>
</html>

app/views/tweets/_footer.html.erb
Copyright &copy; Kindai University 2020 All Rights Reserved.

app/views/tweets/_header.html.erb
<!--<img src="/assets/a.png">-->
<%= image_tag 'header.jpg', class: "headerimg" %>

<p> 


<%= image_tag (src='aicon2.png'),class: "icon" %>
<%=  link_to 'ツイート',new_tweet_path, class: "twitter1" %>
<%=  link_to 'フォロー',new_tweet_path, class: "twitter1" %>
<%=  link_to 'フォロワー',new_tweet_path, class: "twitter1" %>
<%=  link_to 'いいね',new_tweet_path, class: "twitter1" %>


</p> 

app/views/tweets/_sidebar.html.erb
<body>
<div id="pageBody">
<h2>
    近畿大学
</h2>
<p id="pagegray">@kinkidaigakuPR</p>
<p>近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。個別のお問い合わせには返信を行っておりませんので、ご了承ください。</p>

<p>
    <%= link_to 'ツイート',tweets_new_path, class: 'btn btn--orange btn--radius' %>
    <%= link_to 'ダイレクトメール',tweets_new_path, class: 'btn btn--orange btn--radius'  %>
    </p>
</div>

</body>

app/views/tweets/edit.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
 <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
 <% end %>
</ul>
<% end %>

<%= form_for @tweet , message:{action: :update} do |f| %>
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>
<%= f.submit '更新' %>
<% end %>

app/views/tweets/index.html.erb
<div class="first">

<% if flash[:notice] %>
 <%= flash[:notice] %>
<% end %>
<ul>
 
<%=  link_to 'ツイート',new_tweet_path, class: "twitter" %>
<%= link_to 'ツイートと返信',new_tweet_path, class: "twitter" %>
<%= link_to 'ツイートメディア',new_tweet_path, class: "twitter" %>
</ul>

<% @tweets.each do |tweet| %>

 <p>
     <%= tweet.message %>
     
     <% time = ((Time.current.to_i - tweet.tdate.to_i) / 60) %>
     
     <%= "#{time}分前" %>
    <br>
     <%= link_to '削除', tweet_path(tweet.id), method: :delete, class: "CRUD" %>
     <%= link_to '表示', tweet_path(tweet.id), class: "CRUD" %>
     <%= link_to '編集', edit_tweet_path(tweet.id), class: "CRUD" %>
     
 </p>
<% end %>
</div>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
 <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
 <% end %>
</ul>
<% end %>


<%= form_for @tweet ,message:{action: :create} do |f| %>
 <%= f.label :message, 'メッセージ' %>
 <%= f.text_field :message %>
 <%= f.label :tdate, '日付' %>
 <%= tdate = Time.current %>
 <%= f.submit '登録' %>
<% end %>

app/views/tweets/show.html.erb
<p>
    <strong>メッセージ：</strong>
    <%= @tweet.message %>
</p>

<p>
    <strong>日付：</strong>
    <%= @tweet.tdate %>
</p>

<%= link_to 'Back','/' %>